CREATE TABLE phrases (
id INTEGER PRIMARY KEY AUTOINCREMENT,
date_create DATETIME,
date_update DATETAIME,
knowledge_level TEXT,  -- Уровень знания
appemtps_count INTEGER DEFAULT 0,
id_en INTEGER,
id_ru INTEGER,
FOREIGN KEY (id_en) REFERENCES en (id) ON DELETE CASCADE,
FOREIGN KEY (id_ru) REFERENCES ru (id) ON DELETE CASCADE 
);

CREATE TABLE en (
id INTEGER PRIMARY KEY AUTOINCREMENT,
en_value TEXT NOT NULL);

CREATE TABLE ru (
id INTEGER PRIMARY KEY AUTOINCREMENT,
ru_value TEXT NOT NULL);
